In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:

os.getcwd()

'c:\\Users\\Swath\\Desktop\\game dev\\.vscode\\Movie recommendation system'

In [3]:
movie_data = pd.read_csv('movies.csv')
movie_data

index     budget                                    genres  \
0         0  237000000  Action Adventure Fantasy Science Fiction   
1         1  300000000                  Adventure Fantasy Action   
2         2  245000000                    Action Adventure Crime   
3         3  250000000               Action Crime Drama Thriller   
4         4  260000000          Action Adventure Science Fiction   
...     ...        ...                                       ...   
4798   4798     220000                     Action Crime Thriller   
4799   4799       9000                            Comedy Romance   
4800   4800          0             Comedy Drama Romance TV Movie   
4801   4801          0                                       NaN   
4802   4802          0                               Documentary   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     culture clash future space war space colony so...                en   
1     ocean drug abuse exotic island east india trad...                en   
2            spy based on novel secret agent sequel mi6                en   
3     dc comics crime fighter terrorist secret ident...                en   
4     based on novel mars medallion space travel pri...                en   
...                                                 ...               ...   
4798  united states\u2013mexico barrier legs arms pa...                es   
4799                                                NaN                en   
4800  date love at first sight narration investigati...                en   
4801                                                NaN                en   
4802               obsession camcorder crush dream girl                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2     A cryptic message from Bond’s past sends him o...  107.376788  ...   
3     Following the death of District Attorney Harve...  112.312950  ...   
4     John Carter is a war-weary, former military ca...   43.926995  ...   
...                                                 ...         ...  ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...   
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...   
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...   
4802  Ever since the s

In [4]:
#index, homepage, id, overview, original_title, release_date, overview, runtime, crew, vote_average, production_company, production_country, spoken_language and vote_count not needed to find order of recommendations
movie_data = movie_data.drop(['homepage','id','original_title','release_date', 'overview', 'index', 'runtime', 'vote_count', 'crew', 'vote_average', 'production_companies', 'production_countries', 'spoken_languages'], axis=1)
movie_data

budget                                    genres  \
0     237000000  Action Adventure Fantasy Science Fiction   
1     300000000                  Adventure Fantasy Action   
2     245000000                    Action Adventure Crime   
3     250000000               Action Crime Drama Thriller   
4     260000000          Action Adventure Science Fiction   
...         ...                                       ...   
4798     220000                     Action Crime Thriller   
4799       9000                            Comedy Romance   
4800          0             Comedy Drama Romance TV Movie   
4801          0                                       NaN   
4802          0                               Documentary   

                                               keywords original_language  \
0     culture clash future space war space colony so...                en   
1     ocean drug abuse exotic island east india trad...                en   
2            spy based on novel secret agent sequel mi6                en   
3     dc comics crime fighter terrorist secret ident...                en   
4     based on novel mars medallion space travel pri...                en   
...                                                 ...               ...   
4798  united states\u2013mexico barrier legs arms pa...                es   
4799                                                NaN                en   
4800  date love at first sight narration investigati...                en   
4801                                                NaN                en   
4802               obsession camcorder crush dream girl                en   

      popularity     revenue    status  \
0     150.437577  2787965087  Released   
1     139.082615   961000000  Released   
2     107.376788   880674609  Released   
3     112.312950  1084939099  Released   
4      43.926995   284139100  Released   
...          ...         ...       ...   
4798   14.269792     2040920  Released   
4799    0.642552           0  Released   
4800    1.444476           0  Released   
4801    0.857008           0  Released   
4802    1.929883           0  Released   

                                                tagline  \
0                           Enter the World of Pandora.   
1        At the end of the world, the adventure begins.   
2                                 A Plan No One Escapes   
3                                       The Legend Ends   
4                  Lost in our world, found in another.   
...                                                 ...   
4798  He didn't come looking for trouble, but troubl...   
4799  A newlywed couple's honeymoon is upended by th...   
4800                                                NaN   
4801                           A New Yorker in Shanghai   
4802                                                NaN   

                                         title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                                   cast           director  
0     Sam Worthington Zoe Saldana Sigourney Weaver S...      James Cameron  
1     Johnny Depp Orlando Bloom Keira Knightley Stel...     Gore Verbinski  
2     Daniel Craig Christoph Waltz L\u00e9a Seydoux ...         Sam Mendes  
3     Christian Bale Michael Caine Gary Oldman Anne ...  Christopher Nolan  
4     Taylor Kitsch Lynn Collins Samantha Morton Wil...     Andrew Stanton  
...                                                 ...                ...

In [5]:
'''1|if a movie is entered as input then the features whose matching will determine order of recommendationa are:
        1.keywords
        2.genres
        3.original language
        4.cast
        5.director
        6.status
        7.tagline
'''
'''2|After the matching ordering must be done such that the movie with higher:
        1.Profit
        2.Popularity
   comes first.
   
   There there are three steps to find 
'''
#pre-processing genres, keywords and cast
genres = np.array(movie_data['genres'])
for i in range(len(genres)):
    if(type(genres[i])==float):
        genres[i]=[]
        continue
    genres[i]=genres[i].split()

keywords = np.array(movie_data['keywords'])
for i in range(len(keywords)):
    if(type(keywords[i])==float):
        keywords[i]=[]
        continue
    keywords[i]=keywords[i].split()

cast = np.array(movie_data['cast'])
for i in range(len(keywords)):
    if(type(cast[i])==float):
        cast[i]=[]
        continue
    cast[i] = cast[i].split()

title_components = np.array(movie_data['title'])
for i in range(len(keywords)):
    if(type(cast[i])==float):
        title_components[i]=[]
        continue
    title_components[i] = title_components[i].split()

In [6]:
mod_data = pd.DataFrame()
mod_data['genres'] = genres
mod_data['keywords'] = keywords
mod_data['tagline'] = movie_data['tagline']
mod_data['original_language'] =  movie_data['original_language']
mod_data['status'] = movie_data['status']
mod_data['cast'] = cast
mod_data['director'] = movie_data['director']
mod_data['Profit'] = movie_data['revenue']-movie_data['budget']
mod_data['popularity'] = (movie_data['popularity']-movie_data['popularity'].min())/( movie_data['popularity'].max()-movie_data['popularity'].min())
mod_data['title'] = movie_data['title']

mod_data

genres  \
0     [Action, Adventure, Fantasy, Science, Fiction]   
1                       [Adventure, Fantasy, Action]   
2                         [Action, Adventure, Crime]   
3                   [Action, Crime, Drama, Thriller]   
4              [Action, Adventure, Science, Fiction]   
...                                              ...   
4798                       [Action, Crime, Thriller]   
4799                               [Comedy, Romance]   
4800             [Comedy, Drama, Romance, TV, Movie]   
4801                                              []   
4802                                   [Documentary]   

                                               keywords  \
0     [culture, clash, future, space, war, space, co...   
1     [ocean, drug, abuse, exotic, island, east, ind...   
2     [spy, based, on, novel, secret, agent, sequel,...   
3     [dc, comics, crime, fighter, terrorist, secret...   
4     [based, on, novel, mars, medallion, space, tra...   
...                                                 ...   
4798  [united, states\u2013mexico, barrier, legs, ar...   
4799                                                 []   
4800  [date, love, at, first, sight, narration, inve...   
4801                                                 []   
4802         [obsession, camcorder, crush, dream, girl]   

                                                tagline original_language  \
0                           Enter the World of Pandora.                en   
1        At the end of the world, the adventure begins.                en   
2                                 A Plan No One Escapes                en   
3                                       The Legend Ends                en   
4                  Lost in our world, found in another.                en   
...                                                 ...               ...   
4798  He didn't come looking for trouble, but troubl...                es   
4799  A newlywed couple's honeymoon is upended by th...                en   
4800                                                NaN                en   
4801                           A New Yorker in Shanghai                en   
4802                                                NaN                en   

        status                                               cast  \
0     Released  [Sam, Worthington, Zoe, Saldana, Sigourney, We...   
1     Released  [Johnny, Depp, Orlando, Bloom, Keira, Knightle...   
2     Released  [Daniel, Craig, Christoph, Waltz, L\u00e9a, Se...   
3     Released  [Christian, Bale, Michael, Caine, Gary, Oldman...   
4     Released  [Taylor, Kitsch, Lynn, Collins, Samantha, Mort...   
...        ...                                                ...   
4798  Released  [Carlos, Gallardo, Jaime, de, Hoyos, Peter, Ma...   
4799  Released  [Edward, Burns, Kerry, Bish\u00e9, Marsha, Die...   
4800  Released  [Eric, Mabius, Kristin, Booth, Crystal, Lowe, ...   
4801  Released  [Daniel, Henney, Eliza, Coupe, Bill, Paxton, A...   
4802  Released  [Drew, Barrymore, Brian, Herzlinger, Corey, Fe...   

               director      Profit  popularity  \
0         James Cameron  2550965087    0.171815   
1        Gore Verbinski   661000000    0.158846   
2            Sam Mendes   635674609    0.122635   
3     Christopher Nolan   834939099    0.128272   
4        Andrew Stanton    24139100    0.050169   
...                 ...         ...         ...   
4798   Robert Rodriguez     1820920    0.016298   
4799       Edward Burns       -9000    0.000734   
4800        Scott Smith           0    0.001650   
4801        Daniel Hsia           0    0.000979   
4802   Brian Herzlinger           0    0.002204   

                                         title  
0                                       Avatar  
1     Pirates of the Caribbean: At World's End  
2                                      Spectre  
3                        The Dark Knight Rises  
4                                  John Carter  
...

In [7]:
selection = input("Enter Movie Name ")

In [8]:
genre_interest = mod_data[mod_data['title']==selection].iloc[0,0]
l = len(genres)
genre_score = np.zeros(l)
for i in range(l):
    count = 0
    genre_check = mod_data.iloc[i,0]
    for j in genre_check:
        if j in genre_interest:
            count+=1
    genre_score[i] = count/len(genre_interest)
print(genre_score)

[1.  0.5 0.5 ... 0.  0.  0. ]


In [9]:
keywords_interest = mod_data[mod_data['title']==selection].iloc[0,1]
keywords_score = np.zeros(l)
for i in range(l):
    count = 0
    keywords_check = mod_data.iloc[i,1]
    for j in keywords_check:
        if j in keywords_interest:
            count+=1
    keywords_score[i] = count/len(keywords_interest)
print(keywords_score)

[0.    0.125 0.    ... 0.    0.    0.   ]


In [10]:
original_language_interest = mod_data[mod_data['title']==selection].iloc[0,3]
original_language_score = np.zeros(l)
for i in range(l):
    if (original_language_interest == mod_data.iloc[i,3]):
        original_language_score[i] = 1
print(original_language_score)

[1. 1. 1. ... 1. 1. 1.]


In [11]:
status_interest = mod_data[mod_data['title']==selection].iloc[0,4]
status_score = np.zeros(l)
for i in range(l):
    if (status_interest == mod_data.iloc[i,4]):
        status_score[i] = 1
print(status_score)

[1. 1. 1. ... 1. 1. 1.]


In [12]:
cast_interest = mod_data[mod_data['title']==selection].iloc[0,5]
cast_score = np.zeros(l)
for i in range(l):
    count = 0
    cast_check = mod_data.iloc[i,5]
    for j in cast_check:
        if j in cast_interest:
            count+=1
    cast_score[i] = count/len(cast_interest)
print(cast_score)

[0. 0. 0. ... 0. 0. 0.]


In [13]:
tagline_interest = mod_data[mod_data['title']==selection].iloc[0,2]
tagline_score = np.zeros(l)
for i in range(l):
    if (tagline_interest == mod_data.iloc[i,2]):
        tagline_score[i] = 1
        print(i)
print(tagline_score)


68
[0. 0. 0. ... 0. 0. 0.]


In [14]:
director_interest = mod_data[mod_data['title']==selection].iloc[0,6]
director_score = np.zeros(l)
for i in range(l):
    if (director_interest == mod_data.iloc[i,6]):
        director_score[i] = 1
print(director_score)

[0. 0. 0. ... 0. 0. 0.]


In [15]:
title_interest = mod_data[mod_data['title']==selection].iloc[0,9]
title_score = np.zeros(l)
for i in range(l):
    if(mod_data.iloc[i,9][-1].isdigit() and title_interest[-1].isdigit()):
        if (mod_data.iloc[i,9][:-1] == title_interest[:-1]):
            title_score[i] = 1
    elif(mod_data.iloc[i,9][-1].isdigit() and not title_interest[-1].isdigit()):
        if (mod_data.iloc[i,9][:-2] == title_interest):
            title_score[i] = 1
    elif(not mod_data.iloc[i,9][-1].isdigit() and title_interest[-1].isdigit()):
        if (mod_data.iloc[i,9] == title_interest[:-2]):
            title_score[i] = 1
print(title_score)

[0. 0. 0. ... 0. 0. 0.]


In [16]:
mod_data_2 = pd.DataFrame()
mod_data_2['title'] = mod_data['title']
mod_data_2['tagline_score'] = tagline_score
mod_data_2['keywords_score'] = keywords_score
mod_data_2['genre_score'] = genre_score
mod_data_2['original_language_score'] = original_language_score
mod_data_2['status_score'] = status_score
mod_data_2['cast_score'] = cast_score
mod_data_2['director_score'] = director_score
mod_data_2['popularity'] = mod_data['popularity']
mod_data_2['success_of_movie'] = (mod_data['Profit']-mod_data['Profit'].min())/( mod_data['Profit'].max()-mod_data['Profit'].min())
mod_data_2['title_score'] = title_score
mod_data_2['overall_score'] = mod_data_2['keywords_score']*350 + mod_data_2['genre_score']*300+mod_data_2['director_score']*200+mod_data_2['cast_score']*250+mod_data_2['tagline_score']*10000+mod_data_2['original_language_score']*50+mod_data_2['status_score']*30+mod_data_2['popularity']*150+mod_data_2['success_of_movie']*100+mod_data_2['title_score']*1000
# tagline_score>title_score>keyword_score>genre_score>cast_score>director_score>popularity>success_of_movie>original_languge_score>status_score is the weightage order
mod_data_2

title  tagline_score  keywords_score  \
0                                       Avatar            0.0           0.000   
1     Pirates of the Caribbean: At World's End            0.0           0.125   
2                                      Spectre            0.0           0.000   
3                        The Dark Knight Rises            0.0           0.000   
4                                  John Carter            0.0           0.000   
...                                        ...            ...             ...   
4798                               El Mariachi            0.0           0.125   
4799                                 Newlyweds            0.0           0.000   
4800                 Signed, Sealed, Delivered            0.0           0.000   
4801                          Shanghai Calling            0.0           0.000   
4802                         My Date with Drew            0.0           0.000   

      genre_score  original_language_score  status_score  cast_score  \
0            1.00                      1.0           1.0         0.0   
1            0.50                      1.0           1.0         0.0   
2            0.50                      1.0           1.0         0.0   
3            0.25                      1.0           1.0         0.0   
4            1.00                      1.0           1.0         0.0   
...           ...                      ...           ...         ...   
4798         0.25                      0.0           1.0         0.0   
4799         0.00                      1.0           1.0         0.0   
4800         0.00                      1.0           1.0         0.0   
4801         0.00                      1.0           1.0         0.0   
4802         0.00                      1.0           1.0         0.0   

      director_score  popularity  success_of_movie  title_score  overall_score  
0                0.0    0.171815          1.000000          0.0     505.772177  
1                0.0    0.158846          0.304310          0.0     328.007856  
2                0.0    0.122635          0.294987          0.0     277.893959  
3                0.0    0.128272          0.368336          0.0     211.074463  
4                0.0    0.050169          0.069883          0.0     394.513634  
...              ...         ...               ...          ...            ...  
4798             0.0    0.016298          0.061668          0.0     157.361392  
4799             0.0    0.000734          0.060994          0.0      86.209486  
4800             0.0    0.001650          0.060997          0.0      86.347199  
4801             0.0    0.000979          0.060997          0.0      86.246557  
4802             0.0    0.002204          0.060997          0.0      86.430356  

[4803 rows x 12 columns]

In [17]:
pref_order = np.array(mod_data_2.iloc[:,-1]).argsort()[::-1]
mod_data_2[mod_data_2['title']=='Iron Man 2']
st = 'Iron Man 2'
st[-1].isdigit()

True

In [18]:
print("The movies recommended: \n")
for i in range(30):
    print(mod_data_2.iloc[pref_order[i],0])

The movies recommended: 

Iron Man
Iron Man 2
Iron Man 3
The Avengers
Avengers: Age of Ultron
Captain America: Civil War
Ant-Man
Guardians of the Galaxy
X2
Captain America: The Winter Soldier
The Incredible Hulk
X-Men
X-Men: Days of Future Past
Jurassic World
X-Men: The Last Stand
Deadpool
X-Men: First Class
Zathura: A Space Adventure
Man of Steel
Avatar
Captain America: The First Avenger
The Wolverine
Superman II
X-Men Origins: Wolverine
Fantastic Four
Southland Tales
Mad Max: Fury Road
Interstellar
TRON: Legacy
X-Men: Apocalypse
